# -*- coding: utf-8 -*-
"""MLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GU-nBAxxhAN88bLYSaUkj1GJYTOlZGxS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""This block imports all the required libraries for data manipulation, visualization, preprocessing, model building, and evaluation. These libraries provide the necessary tools to perform the Multiple Linear Regression analysis."""

df = pd.read_csv("ToyotaCorolla - MLR.csv")
print(df.head())
print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

df.describe()

"""This block loads the dataset and provides an overview of its structure, including the number of rows and columns, data types, missing values, duplicate records, and summary statistics. This helps understand the dataset before preprocessing."""

le = LabelEncoder()
df["Fuel_Type"] = le.fit_transform(df["Fuel_Type"])


X = df.drop("Price", axis=1)
y = df["Price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""The categorical variable Fuel_Type is converted into numerical values using Label Encoding. The dataset is then divided into features and target, followed by an 80:20 train-test split for model training and evaluation."""

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

df.hist(figsize=(15,10))
plt.tight_layout()
plt.show()

sns.pairplot(df)
plt.show()

"""This block visualizes the dataset using a correlation heatmap, histograms, and pair plots. These visualizations help identify feature relationships, data distribution, and possible trends useful for regression analysis."""

plt.figure(figsize=(15,10))

for i, col in enumerate(df.columns, 1):
    plt.subplot(4,3,i)
    sns.boxplot(y=df[col])

plt.tight_layout()
plt.show()

"""Boxplots are used to detect outliers in each numerical feature. Identifying outliers is important because they can influence the accuracy and stability of the regression model."""

model1 = LinearRegression()
model1.fit(X_train, y_train)

y_pred1 = model1.predict(X_test)

print("MAE :", mean_absolute_error(y_test, y_pred1))
print("MSE :", mean_squared_error(y_test, y_pred1))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred1)))
print("R2 Score:", r2_score(y_test, y_pred1))

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model1.coef_
})

print(coefficients)

"""The first Multiple Linear Regression model is trained using all available features. Its performance is evaluated using MAE, MSE, RMSE, and R² Score, while the coefficients show the impact of each feature on the predicted car price."""

X2 = df[['Age_08_04','KM','HP','Weight']]

X2_train, X2_test, y_train, y_test = train_test_split(
    X2, y, test_size=0.2, random_state=42
)

model2 = LinearRegression()
model2.fit(X2_train, y_train)

y_pred2 = model2.predict(X2_test)

print("R2 Score:", r2_score(y_test, y_pred2))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred2)))

"""The second model uses only a subset of important numerical features. This helps evaluate whether a simpler model can achieve comparable prediction performance."""

X3 = df[['Age_08_04','KM','HP','Automatic','Weight','Fuel_Type']]

X3_train, X3_test, y_train, y_test = train_test_split(
    X3, y, test_size=0.2, random_state=42
)

model3 = LinearRegression()
model3.fit(X3_train, y_train)

y_pred3 = model3.predict(X3_test)

print("R2 Score:", r2_score(y_test, y_pred3))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred3)))

"""The third model includes selected features based on their relevance to the target variable. This optimized feature set aims to improve prediction accuracy while keeping the model efficient."""

results = pd.DataFrame({
    "Model": ["Model 1 (All Features)",
              "Model 2 (Selected Features)",
              "Model 3 (Optimized Features)"],

    "MAE": [
        mean_absolute_error(y_test, y_pred1),
        mean_absolute_error(y_test, y_pred2),
        mean_absolute_error(y_test, y_pred3)
    ],

    "RMSE": [
        np.sqrt(mean_squared_error(y_test, y_pred1)),
        np.sqrt(mean_squared_error(y_test, y_pred2)),
        np.sqrt(mean_squared_error(y_test, y_pred3))
    ],

    "R2 Score": [
        r2_score(y_test, y_pred1),
        r2_score(y_test, y_pred2),
        r2_score(y_test, y_pred3)
    ]
})

results

"""This block compares the performance of the three Multiple Linear Regression models using MAE, RMSE, and R² Score. The comparison helps identify the model that provides the most accurate predictions while maintaining good generalization."""

lasso = Lasso(alpha=1.0)
ridge = Ridge(alpha=1.0)

lasso.fit(X_train, y_train)
ridge.fit(X_train, y_train)

lasso_pred = lasso.predict(X_test)
ridge_pred = ridge.predict(X_test)

regularization_results = pd.DataFrame({
    "Model": ["Lasso Regression", "Ridge Regression"],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, lasso_pred)),
        np.sqrt(mean_squared_error(y_test, ridge_pred))
    ],
    "R2 Score": [
        r2_score(y_test, lasso_pred),
        r2_score(y_test, ridge_pred)
    ]
})

regularization_results

"""Lasso and Ridge Regression are applied to reduce overfitting and improve model stability. Their performance is evaluated using RMSE and R² Score, allowing comparison between the two regularization techniques.

# **conclusion**
The Toyota Corolla dataset was successfully analyzed using Exploratory Data Analysis (EDA), preprocessing techniques, and Multiple Linear Regression models. Three different regression models were developed and evaluated using MAE, MSE, RMSE, and R² Score on the testing dataset. The comparison showed that the optimized model with the selected features achieved the best balance between prediction accuracy and model simplicity. Lasso and Ridge Regression were also applied to reduce overfitting and improve model generalization. Overall, the analysis demonstrates that Multiple Linear Regression is an effective approach for predicting Toyota Corolla prices, with regularization techniques further enhancing the model's robustness and reliability.
"""